# Generated by Django 3.1.7 on 2021-04-17 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0002_auto_20210417_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='tittle',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
    ]
