# Generated by Django 3.1.7 on 2021-04-21 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0004_articles_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='user_id',
            new_name='user',
        ),
    ]
