# Generated by Django 3.1.7 on 2021-04-20 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210420_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='avatar',
        ),
    ]
