# Generated by Django 3.1.7 on 2021-04-20 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('accounts', '0003_remove_user_profile_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_profile',
        ),
    ]
